name: Setup Monorepo
description: Prepare and install everything for the monorepo

inputs:
  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.x

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: pnpm

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        expo-version: latest
        token: ${{ inputs.expo-token }}

    - name: 📦 Install dependencies
      run: pnpm install --no-frozen-lockfile
      shell: bash

    - name: ♻️ Restore cache
      uses: actions/cache@v3
      with:
        key: turbo-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ runner.os }}
        path: |
          node_modules/.cache/turbo
          apps/*/.turbo
          packages/*/.turbo
